# ==============================================================================
# ������ 사용자 전용 랜덤 아이템 풀 (기존 리스트 유지)
# ==============================================================================
module RandomItemPool
  # --- 1. 메가스톤 ---
  MEGA_STONES = [
    :VENUSAURITE, :CHARIZARDITEX, :CHARIZARDITEY, :BLASTOISINITE, :BEEDRILLITE,
    :PIDGEOTITE, :ALAKAZITE, :SLOWBRONITE, :GENGARITE, :KANGASKHANITE,
    :PINSIRITE, :GYARADOSITE, :AERODACTYLITE, :DRAGONITENITE, :MEGANIUMITE, :FERALIGITE,
    :AMPHAROSITE, :STEELIXITE, :SCIZORITE, :HERACRONITE, :HOUNDOOMINITE,
    :TYRANITARITE, :SCEPTILITE, :BLAZIKENITE, :SWAMPERTITE, :GARDEVOIRITE,
    :SABLENITE, :MAWILITE, :AGGRONITE, :MEDICHAMITE, :MANECTITE, :SHARPEDONITE,
    :CAMERUPTITE, :ALTARIANITE, :BANETTITE, :ABSOLITE, :GLALITITE, :SALAMENCITE,
    :METAGROSSITE, :LOPUNNITE, :GARCHOMPITE, :LUCARIONITE, :DIANCITE,
    :ABOMASITE, :GALLADITE, :EMBOARITE, :AUDINITE, :DRAMPANITE, :LATIASITE, :LATIOSITE, :MEWTWONITEX, :MEWTWONITEY,
    :CLEFABLITE, :VICTREEBELITE, :STARMINITE, :SKARMORITE, :FROSLASSITE,
    :EXCADRITE, :SCOLIPITE, :SCRAFTINITE, :EELEKTROSSITE, :CHANDELURITE,
    :CHESNAUGHTITE, :DELPHOXITE, :GRENINJITE, :PYROARITE, :FLOETTITE,
    :MALAMARITE, :BARBARACITE, :DRAGALGITE, :HAWLUCHANITE, :ZYGARDITE,
    :FALINKSITE, :RAICHUNITEX, :RAICHUNITEY, :CHIMECHITE, :ABSOLITEZ,
    :STARAPTITE, :GARCHOMPITEZ, :LUCARIONITEZ, :HEATRANITE, :DARKRANITE,
    :GOLURKITE, :MEOWSTICITE, :CRABOMINITE, :GOLISOPITE, :MAGEARNITE,
    :ZERAORITE, :SCOVILLAINITE, :GLIMMORANITE, :TATSUGIRINITE, :BAXCALIBRITE
  ]

  # --- 2. Z크리스탈 ---
  Z_CRYSTALS = [
    :NORMALIUMZ, :FIRIUMZ, :WATERIUMZ, :ELECTRIUMZ, :GRASSIUMZ,
    :ICIUMZ, :FIGHTINIUMZ, :POISONIUMZ, :GROUNDIUMZ, :FLYINIUMZ,
    :PSYCHIUMZ, :BUGINIUMZ, :ROCKIUMZ, :GHOSTIUMZ, :DRAGONIUMZ,
    :DARKINIUMZ, :STEELIUMZ, :FAIRIUMZ,
    :ALORAICHIUMZ, :DECIDIUMZ, :EEVIUMZ, :INCINIUMZ,
    :KOMMONIUMZ, :LYCANIUMZ, :MARSHADIUMZ, :MEWNIUMZ,
    :MIMIKIUMZ, :PIKANIUMZ, :PIKASHUNIUMZ, :PRIMARIUMZ,
    :SNORLIUMZ, :SOLGANIUMZ, :TAPUNIUMZ, :ULTRANECROZIUMZ
  ]

  # --- 3. 육성 아이템 ---
  CANDIES = [
    :RARECANDY, :EXPCANDYXS, :EXPCANDYS, :EXPCANDYM, :EXPCANDYL, :EXPCANDYXL,
    :ADAPTIVELEVELCANDY, :SHINYCANDY, :BLACKAUGURITE, :ABILITYCAPSULE, :ABILITYPATCH
  ]

  # --- 4. 배틀 소지품 및 진화 도구 ---
  BATTLE_ITEMS = [
    :WEAKNESSPOLICY, :BLUNDERPOLICY, :ROOMSERVICE, :EJECTBUTTON, :EJECTPACK,
    :REDCARD, :WHITEHERB, :POWERHERB, :MENTALHERB, :MIRRORHERB,
    :THROATSPRAY, :ADRENALINEORB, :ABSORBBULB, :CELLBATTERY, :LUMINOUSMOSS, :SNOWBALL,
    :LIGHTBALL, :THICKCLUB, :LUCKYPUNCH, :QUICKPOWDER, :METALPOWDER,
    :STICK, :LEEK, :EVIOLITE, :ASSAULTVEST, :ADAMANTORB, :ADAMANTCRYSTAL, :LUSTROUSORB, :LUSTROUSGLOBE,
    :GRISEOUSORB, :GRISEOUSCORE, :RUSTEDSWORD, :RUSTEDSHIELD,
    :BOOSTERENERGY, :HEARTHFLAMEMASK, :CORNERSTONEMASK, :WELLSPRINGMASK, :SOULDEW,
    :REDORB, :BLUEORB, :PRISONBOTTLE, :REVEALGLASS, :DNASPLICERS, :NSOLARIZER, :NLUNARIZER,
    :AIRBALLOON, :BRIGHTPOWDER, :ROCKYHELMET, :SAFETYGOGGLES, :HEAVYDUTYBOOTS,
    :UTILITYUMBRELLA, :CHOICEBAND, :CHOICESPECS, :CHOICESCARF, :LIFEORB,
    :FOCUSSASH, :FLAMEORB, :TOXICORB, :METRONOME, :LEFTOVERS, :BLACKSLUDGE,
    :LUCKYEGG, :AMULETCOIN, :KINGSROCK, :QUICKCLAW, :SCOPELENS, :SHELLBELL,
    :WIDELENS, :WISEGLASSES, :ZOOMLENS, :BIGROOT, :BINDINGBAND, :GRIPCLAW,
    :CHARCOAL, :MYSTICWATER, :MAGNET, :MIRACLESEED, :NEVERMELTICE,
    :BLACKBELT, :POISONBARB, :SOFTSAND, :SHARPBEAK, :TWISTEDSPOON,
    :SILVERPOWDER, :HARDSTONE, :SPELLTAG, :DRAGONFANG, :BLACKGLASSES, :METALCOAT,
    :DRACOPLATE, :DREADPLATE, :EARTHPLATE, :FISTPLATE, :FLAMEPLATE, :ICICLEPLATE,
    :INSECTPLATE, :IRONPLATE, :MINDPLATE, :PIXIEPLATE, :SKYPLATE, :SPLASHPLATE,
    :SPOOKYPLATE, :STONEPLATE, :TOXICPLATE, :ZAPPLATE, :MEADOWPLATE,
    :BUGMEMORY, :DARKMEMORY, :DRAGONMEMORY, :ELECTRICMEMORY, :FAIRYMEMORY,
    :FIREMEMORY, :FLYINGMEMORY, :GHOSTMEMORY, :GRASSMEMORY, :GROUNDMEMORY,
    :ICEMEMORY, :POISONMEMORY, :PSYCHICMEMORY, :ROCKMEMORY, :STEELMEMORY, :WATERMEMORY,
    :FIRESTONE, :THUNDERSTONE, :WATERSTONE, :LEAFSTONE, :MOONSTONE, :SUNSTONE, 
    :DUSKSTONE, :DAWNSTONE, :SHINYSTONE, :ICESTONE, :DRAGONSCALE, :UPGRADE, 
    :PROTECTOR, :ELECTIRIZER, :MAGMARIZER, :DUBIOUSDISC, :REAPERCLOTH, 
    :PRISMSCALE, :WHIPPEDDREAM, :SACHET, :LINKINGCORD, :RAZORCLAW, :RAZORFANG
  ]

  # --- 5. 병뚜껑 ---
  BOTTLECAPS = [:BOTTLECAP, :GOLDBOTTLECAP]
end

# ===============================
# 맵 아이템 랜덤 적용 (버그 수정판)
# ===============================
alias __random_item_original_pbItemBall pbItemBall

def pbItemBall(item, quantity = 1)
  # [수정 포인트] 초기값을 false에서 true로 변경하여 "기본 켜짐" 상태로 만듭니다.
  $random_item_switch = true if $random_item_switch.nil? 

  if $random_item_switch
    item_data = GameData::Item.get(item)
    
    # 금지 목록
    excluded_list = [:REDCONTROLLER, :SHINYCANDY, :ADAPTIVELEVELCANDY]
    
    if !excluded_list.include?(item) && !item_data.is_key_item?
      if item_data.is_TM?
        all_tms = GameData::Item.keys.select { |i| GameData::Item.get(i).is_TM? }
        item = all_tms.sample unless all_tms.empty?
      else
        item = RandomItemSystem.get_random_item
      end
    end
  end
  
  __random_item_original_pbItemBall(item, quantity)
end

# ===============================
# ������ 확률 분리 랜덤 시스템 (v21.1 최적화)
# ===============================
module RandomItemSystem
  CHANCE_BATTLE  = 60
  CHANCE_Z_ITEM  = 15
  CHANCE_MEGA    = 15
  CHANCE_CANDY   = 5
  CHANCE_CAPS    = 5

  def self.valid(list)
    list.select { |id| GameData::Item.exists?(id) }
  end

  def self.get_random_item
    battle  = valid(RandomItemPool::BATTLE_ITEMS)
    zitems  = valid(RandomItemPool::Z_CRYSTALS)
    megas   = valid(RandomItemPool::MEGA_STONES)
    candies = valid(RandomItemPool::CANDIES)
    caps    = valid(RandomItemPool::BOTTLECAPS)

    roll = rand(100)
    if roll < CHANCE_BATTLE
      return battle.sample || :POTION
    elsif roll < CHANCE_BATTLE + CHANCE_Z_ITEM
      return zitems.sample || :POTION
    elsif roll < CHANCE_BATTLE + CHANCE_Z_ITEM + CHANCE_MEGA
      return megas.sample || :POTION
    elsif roll < CHANCE_BATTLE + CHANCE_Z_ITEM + CHANCE_MEGA + CHANCE_CANDY
      return candies.sample || :POTION
    else
      return caps.sample || :POTION
    end
  end
end