TRAINER_ABILITIES = [
  :SPEEDBOOST, :LIBERO, :PROTEAN, :MAGICBOUNCE, :MULTISCALE, :TERAFORMZERO,
  :SHADOWSHIELD, :PARENTALBOND, :INTIMIDATE, :REGENERATOR, :PRANKSTER,
  :WELLBAKEDBODY, :WATERABSORB, :MOTORDRIVE, :SAPSIPPER, :VOLTABSORB, #공격무효
	:FLASHFIRE, :LIGHTNINGROD, :STORMDRAIN,:WINDRIDER, #공격무효
	:POISONPOINT, :STATIC, :EFFECTSPORE, :FLAMEBODY, #상태이상
	:HUGEPOWER,:PUREPOWER, :ASONECHILLINGNEIGH,:ASONEGRIMNEIGH,:MOXIE,:BEASTBOOST,:SOULHEART,  #스텟증가
  :DAUNTLESSSHIELD, :INTREPIDSWORD,
	:VESSELOFRUIN, :SWORDOFRUIN, :TABLETSOFRUIN, :BEADSOFRUIN,
	:STAMINA, :CONTRARY,
	:SOLARPOWER,:FLOWERGIFT,
	:GUTS,:QUICKFEET, :MARVELSCALE, #상태이상
	:LEVITATE,:ADAPTABILITY, :GALEWINGS,
  :IRONBARBS, :TECHNICIAN, :SERENEGRACE,
	:AERILATE,:PIXILATE,:REFRIGERATE,:GALVANIZE, #스킨
  :UNBURDEN, :UNNERVE,:TOUGHCLAWS,
  :TOXICCHAIN, :POISONTOUCH,:TOXICDEBRIS, #독
  :MAGICGUARD,:PERISHBODY, :FULLMETALBODY,
  :MIRRORARMOR,:MOODY, :UNSEENFIST, :COMPOUNDEYES, :FLUFFY, 
  :NEUROFORCE, :DAZZLING, :TINTEDLENS, :WATERBUBBLE,
  :MINDSEYE,#심안
  :THERMALEXCHANGE,
  :SHEERFORCE, :SHIELDDUST,:PURIFYINGSALT,
  :UNAWARE, :SUPREMEOVERLORD,:FURCOAT, :PRISMARMOR,
	:ICESCALES, :POISONHEAL,
	:ORICHALCUMPULSE, :HADRONENGINE, :GRASSYSURGE,:MISTYSURGE,:PSYCHICSURGE,:ELECTRICSURGE,
	:DELTASTREAM,:CURSEDBODY,:INNARDSOUT,:DARKAURA,:FAIRYAURA,:DOWNLOAD, :SIMPLE,:SUPERLUCK,
	:TRACE,:PRESSURE,:NOGUARD,
].uniq

POWER_POKEMON = [
	:ABOMASNOW_1,:ABSOL_1,:AERODACTYL_1,:AGGRON_1,:ALAKAZAM_1,:ALTARIA_1,
	:AMPHAROS_1,:AUDINO_1,:BANETTE_1,:BEEDRILL_1,:BLASTOISE_1,:BLAZIKEN_1,:CAMERUPT_1,
	:CHARIZARD_1,:CHARIZARD_2,:DIALGA_1,:DIANCIE_1,:ETERNATUS_1,:GALLADE_1,
	:GARCHOMP_1,:GARDEVOIR_1,:GENGAR_1,:GIRATINA_1,:GLALIE_1,:GROUDON_1,
	:GYARADOS_1,:HERACROSS_1,:HOOPA_1,:HOUNDOOM_1,:KANGASKHAN_1,:KELDEO_1,:KYOGRE_1,
	:KYUREM_2,:KYUREM_4,:LANDORUS_1,:LATIAS_1,:LATIOS_1,:LOPUNNY_1,:LUCARIO_1,:MANECTRIC_1,
	:MAWILE_1,:MEDICHAM_1,:METAGROSS_1,:MEWTWO_1,:MEWTWO_2,:PALKIA_1,:PIDGEOT_1,:PINSIR_1,
	:RAYQUAZA_1,:SABLEYE_1,:SALAMENCE_1,:SCEPTILE_1,:SCIZOR_1,:SHARPEDO_1,:SLOWBRO_1,:STEELIX_1,
	:SWAMPERT_1,:THUNDURUS_1,:TORNADUS_1,:TYRANITAR_1,:VENUSAUR_1,:ZACIAN_1,:ZAMAZENTA_1,
	:NECROZMA_2,:NECROZMA_1,:NECROZMA_3,:ZYGARDE_2,:ARTICUNO_1,:CALYREX_1,:CALYREX_2,
	:GRENINJA_2,:MOLTRES_1,:URSALUNA_1,:URSHIFU_1,:ZAPDOS_1,
	:SCRAFTY_1,:DRAMPA_1,:SKARMORY_1,:RAICHU_3,:RAICHU_2,:CHESNAUGHT_1,:STARMIE_1,:EXCADRILL_1,
	:PYROAR_1,:MALAMAR_1,:HAWLUCHA_1,:CLEFABLE_1,:FALINKS_1,:GRENINJA_3,:SCOLIPEDE_1,
	:VICTREEBEL_1,:DELPHOX_1,:CHANDELURE_1,:ZYGARDE_4,:FROSLASS_1,:DRAGONITE_1,
	:DRAMPA_1,:SCRAFTY_1,:MEGANIUM_1,:CLEFABLE_1,
].uniq

ANOTHER_FORM_TRAINER = [
	:AVALUGG_1,:DECIDUEYE_1,:GOODRA_1,:BRAVIARY_1,:ZOROARK_1,:LILLIGANT_1,
	:SAMUROTT_1,:TYPHLOSION_1,:ARCANINE_1,:ELECTRODE_1,:RAICHU_1,:NINETALES_1,:GOLEM_1,
	:MUK_1,:EXEGGUTOR_1,:DARMANITAN_2,
].uniq

TO_REMOVE_MOVE = [
  :MISTYEXPLOSION, :LUNARDANCE, :HEALINGWISH, :SELFDESTRUCT,
  :WORRYSEED, :SKILLSWAP, :ROLEPLAY, :GASTROACID,
  :ENTRAINMENT, :SIMPLEBEAM, :COVET, :PLUCK,
  :BUGBITE, :THIEF, :RECYCLE, :FLING,:SOLARBLADE,:SKYATTACK,:SKULLBASH,
	:RAZORWIND,:BIDE,:BOUNCE,:DIG,:FLY,:DIVE,:PHANTOMFORCE,:IMPRISON,:DISABLE,
	:TORMENT,:HEALBLOCK,:JAWLOCK,:FAIRYLOCK,:OCTOLOCK,:ANCHORSHOT,:MEANLOOK,:BLOCK,
	:SPIDERWEB,:WRAP,:CLAMP,:TELEPORT,:SECRETPOWER,:HEADBUTT,:ROCKSMASH,:FLASH,:CUT,:ROCKCLIMB,:SWEETSCENT,:MILKDRINK,
	:STRENGTH,:DEFOG,:PRESENT,:GYROBALL,:FRUSTRATION,:ELECTROBALL,:LOWKICK,:RETURN,
	:STEAMROLLER,:STOMP,:MAGNITUDE,:TWISTER,:SKYUPPERCUT,:GUST,:GRASSPLEDGE,
	:FIREPLEDGE,:WATERPLEDGE,:ROUND,:SMELLINGSALT,:WAKEUPSLAP,:ASSURANCE,:BRINE,
	:STOMPINGTANTRUM,:PAYBACK,:AVALANCHE,:PSYWAVE,:SEISMICTOSS,:DRAGONRAGE,:SONICBOOM,:NIGHTSHADE,
	:POWERTRIP,:MUDSLAP,:SPIKECANNON,:ABSORB,:FURYSWIPES,:SMOG,:ARMTHRUST,:PECK,:LICK,:DOUBLEKICK,
	:ASTONISH,:FEINT,:BARRAGE,:POISONSTING,:FURYATTACK,:PAYDAY,:SCRATCH,:DOUBLESAP,:POUND,
	:TRIPLEKICK,:CONSTRICT,:ELECTRICTERRAIN,:ACID,:GRASSYTERRAIN,:QUASH,:BUBBLE,:TRICKORTREAT,:REFLECTTYPE,
	:TACKLE,:MATBLOCK,:MAGICROOM,:BESTOW,:AFTERYOU,:MISTYTERRAIN,:SOAK,:FALSESWIPE,:PSYCHICTERRAIN,
	:HOLDBACK,:CRUSHGRIP,:TELEKINESIS,:PURSUIT,:CUT,:DEFENDORDER,
	:ROTOTILLER,:IONDELUGE,:FORESTSCURSE,:CRAFTYSHIELD,:CAPTIVATE,:SHARPEN,:MEDITATE,:KINESIS,:STRINGSHOT,:SPLASH,
	:SANDATTACK,:WITHDRAW,:GROWL,:MIST,:TAILWHIP,:HARDEN,:AURORAVEIL,:SPEEDSWAP,:PURIFY,:HAZE,:ROAR,:LUCKYCHANT,
	:ACIDARMOR,:SMOKESCREEN,:TRUMPCARD,:MAGNETRISE,:ELECTRIFY,:SLEEPTALK,:MINDREADER,:CONVERSION,:SPIDERWEB,
	:FLAIL,:ENDURE,:CONFIDE,:SPITE,:SPOTLIGHT,:FAIRYLOCK,:NIGHTMARE,:AROMATICMIST,:PLAYNICE,:GEARUP,:VENOMDRENCH,
	:MAGNETICFLUX,:LASERFOCUS,:FLOWERSHIELD,:HAPPYHOUR,:POWDER,:CONVERSION2,:HOLDHANDS,:CELEBRATE,:LOCKON,
	:BABYDOLLEYES,:COTTONSPORE,:BEATUP,:FORESIGHT,:SCARYFACE,:SAFEGUARD,:HEALBELL,:ATTRACT,:PSYCHUP,:SWEETSCENT,
	:TICKLE,:CHARGE,:FAKETEARS,:STOCKPILE,:SPITUP,:MUDSPORT,:SWALLOW,
	:ODORSLEUTH,:GRUDGE,:AROMATHERAPY,:MEFIRST,:CAMOUFLAGE,:MIRACLEEYE,:ACUPRESSURE,:WATERSPORT,:EMBARGO,
	:HEALPULSE
].uniq
TO_ADD_MOVE = [
  :SHIFTGEAR,:KINGSHIEILD,:BANEFULBUNKER,:SALTCURE,:SURGINGSTRIKES,:PARTINGSHOT,
	:NASTYPLOT,:DRAGONDANCE,:DESTINYBOND,:CURSE,:QUIVERDANCE,:REFLECT,:LIGHTSCREEN,:COSMICPOWER,
	:CALMMIND,:TAILWIND,:TOXIC,:ICESHARD,:SPORE,:SWORDSDANCE,:LEECHSEED,:TRIPLEAXEL,:COTTONGUARD,
	:RECOVER,:ICICLESPEAR,:STRENGTHSAP,:ENCORE,:SHELLSMASH,:THUNDERWAVE,:YAWN,:WILLOWISP,:GLARE,
].uniq
ATK_MOVE = [
	:DRAGONDANCE,:BELLYDRUM,:SWORDSDANCE,:HONECLAWS,
].uniq
SATK_MOVE=[
	:NASTYPLOT,:CALMMIND,:COIL,:TAILGLOW,
].uniq